### ISSUE TITLE
How to get the result of Table 1?

### ISSUE THREAD

**Issue by HaoranZhao1988** [bhheo/BSS_distillation#1]
very interesting work,and i want to ask how to get the result of Table 1? Do you have the repositories about FSP and FITNET  and AT?

**Comment by bhheo** [comment]
Thank you for your interest in my work.

The result of "train_BSS_distillation.py" is "proposed" in Table 1.
"Hinton" in Table 1 can be obtained by removing KD loss for BSS (line 141).
"Original" is training without the KD loss (line 102) and KD loss for BSS (line 141).
If you want to change the student network, please change line 61.

In case of FITNET, AT and FSP, we implemented it based on papers.
This code is not the author's official code, so it will not be uploaded to github.

There is a code of "AT" implemented by the author. (https://github.com/szagoruyko/attention-transfer)
This will help to implement FITNET and FSP.
